apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-client-info-external
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-info.yml: "{{ .client_info }}"
  data:
    - secretKey: client_info
      remoteRef:
        key: synology-csi-client-info
