apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-db
  labels:
    db: commafeed-db
spec:
  instances: 3
  storage:
    storageClass: synology-retain
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: commafeed
      owner: commafeed
      secret:
        name: commafeed-env
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: commafeed-backup-storage
  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: commafeed-backup-storage
          serverName: commafeed-db-backup
