apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: commafeed
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  rules:
    - host: commafeed.leehosanganson.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: commafeed
                port:
                  number: 8082

  tls:
    - hosts:
        - commafeed.leehosanganson.dev
      secretName: commafeed-tls
