apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
data:
  DB_TYPE: postgresdb
  DB_POSTGRESDB_HOST: n8n-db
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: n8n
  N8N_PROTOCOL: http
  N8N_PORT: "5678"
