resources:
  - ../../paperless-ngx/overlays/default
  - ../../home-assistant/overlays/default
  - ../../zotero-webdav/overlays/default

labels:
  - includeSelectors: false
    pairs:
      backups: enabled
      environment: production
