apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-model-cache-pvc
spec:
  storageClassName: "nfs-csi-retain"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
