apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: n8n-backup-storage
spec:
  configuration:
    destinationPath: https://lhshomelabbackup.blob.core.windows.net/n8n
    azureCredentials:
      storageAccount:
        name: n8n-backup-env
        key: storage-account-name
      storageSasToken:
        name: n8n-backup-env
        key: blob-sas
    wal:
      compression: gzip
    data:
      compression: gzip
  retentionPolicy: 7d
