apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  labels:
    db: n8n-db
spec:
  instances: 3
  storage:
    storageClass: synology-retain
    size: 30Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: n8n
      owner: n8n
      secret:
        name: n8n-env
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: n8n-backup-storage
  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: n8n-backup-storage
          serverName: n8n-db-backup
