apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: karakeep-nextauth-secret
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: karakeep-meilisearch-master-key
    - secretKey: NEXT_PUBLIC_SECRET
      remoteRef:
        key: karakeep-next-public-secret
