resources:
  - github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v7.0.2
  - github.com/kubernetes-csi/external-snapshotter/deploy/kubernetes/snapshot-controller?ref=v7.0.2
  - namespace.yml
  - controller.yml
  - csi-driver.yml
  - node.yml
  - storage-class.yml
  - snapshotter/snapshotter.yaml
  - snapshotter/volume-snapshot-class.yml
  - storageclass/nfs.yaml
  - storageclass/synology-default.yaml
  - storageclass/synology-retain.yaml
