apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: actual-budget
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  ingressClassName: traefik
  rules:
    - host: actual-budget.homelab.leehosanganson.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: actual-budget
                port:
                  number: 80
  tls:
    - hosts:
        - actual-budget.homelab.leehosanganson.dev
      secretName: actual-budget-tls
