apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zotero-webdav
spec:
  interval: 1h
  chart:
    spec:
      chart: webdav
      version: 0.0.7
      sourceRef:
        kind: HelmRepository
        name: danuk
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: zotero-webdav-values
