resources:
  - ../../helm
  - ../../cloudflare/overlays/default
  - ../../cert-manager/overlays/default
  - ../../synology-csi/overlays/default
  - ../../velero/overlays/default
  - ../../external-secrets/overlays/default

labels:
  - includeSelectors: false
    pairs:
      backups: enabled
      environment: production
