resources:
  - ../../helm
  - ../../cloudflare/overlays/default
  - ../../cert-manager/overlays/default

labels:
  - includeSelectors: false
    pairs:
      backups: enabled
      environment: production
