apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft1
spec:
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: 4.26.3
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: minecraft1-values
