apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-secrets-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: gluetun-secrets
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: wireguard-private-key
