apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: litellm-backup-schedule
spec:
  cluster:
    name: litellm-db
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
