apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: bazarr-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: jellyfin-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: jellyseerr-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: prowlarr-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: qbit-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: radarr-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  template:
    metadata:
      annotations:
        backup.velero.io/backup-volumes: sonarr-pvc
