apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-configmap
data:
  USERMAP_UID: "1000"
  USERMAP_GID: "1000"

  S6_READ_ONLY_ROOT: "1"
  S6_VERBOSITY: "2"
  S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"

  PAPERLESS_PORT: "8000"
  PAPERLESS_DB_HOST: paperless-db
  PAPERLESS_DB_PORT: "5432"
  PAPERLESS_REDIS: "redis://broker:6379"
  PAPERLESS_TIME_ZONE: "Europe/London"
  PAPERLESS_URL: "https://paperless.homelab.leehosanganson.dev"
  PAPERLESS_SOCIAL_AUTO_SIGNUP: "true"
  PAPERLESS_DISABLE_REGULAR_LOGIN: "true"
  PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"

  PAPERLESS_CONSUMPTION_DIR: /usr/src/paperless-ngx/consume
  PAPERLESS_DATA_DIR: /usr/src/paperless-ngx/data
  PAPERLESS_EXPORT_DIR: /usr/src/paperless-ngx/export
  PAPERLESS_MEDIA_ROOT: /usr/src/paperless-ngx/media

  PAPERLESS_CONSUMER_POLLING: "60"
  PAPERLESS_CONSUMER_RECURSIVE: "true"
  PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
