apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: paperless-db
  labels:
    db: paperless-db
spec:
  instances: 3
  storage:
    storageClass: synology-retain
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: paperless-env
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: paperless-backup-storage
  externalClusters:
    - name: clusterBackup
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: paperless-backup-storage
          serverName: paperless-db-backup
