apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-env-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: paperless-env
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: paperless-db-username
    - secretKey: password
      remoteRef:
        key: paperless-db-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-backup-env-external
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: paperless-backup-env
    creationPolicy: Owner
  data:
    - secretKey: storage-account-name
      remoteRef:
        key: homelab-backup-storageaccount-name
    - secretKey: blob-sas
      remoteRef:
        key: paperless-blob-sas
